services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s


  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DBURL=postgres://postgres:postgres@db:5432/products?sslmode=disable
      - ServerHost=0.0.0.0
      - ServerPort=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy