version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/server{{if eq OS "windows"}}.exe{{end}} cmd/server/main.go
    desc: Build the Go binary

  test:
    cmds:
      - go test -v -coverpkg=./... ./...
    desc: Run tests

  run:
    cmds:
      - task: build
      - bin/server{{if eq OS "windows"}}.exe{{end}}
    desc: Build and run the application

  fmt:
    cmds:
      - go fmt ./...

  lint:
    cmds:
      - golangci-lint run
    desc: Run linting tool

  migration:
    cmds:
      - migrate create -ext psql -dir migrations "{{.ARGS}}"
    desc: Create a new migration
    vars:
      ARGS: ""
    silent: true

  migrate-up:
    cmds:
      - go run cmd/migration/main.go --direction=up
    desc: Run migrations up

  migrate-down:
    cmds:
      - go run cmd/migration/main.go --direction=down
    desc: Run migrations down
